import { jsPDF } from "jspdf";
import { useEffect, useState } from "react";
import axios from "axios";


// const downloadPDF = (report) => {
//   const doc = new jsPDF();

//   doc.setFontSize(18);
//   doc.text("AI Medical Report", 20, 20);

//   doc.setFontSize(12);
//   doc.text(`Diagnosis: ${report.diagnosis}`, 20, 40);
//   doc.text(`Symptoms: ${report.symptoms}`, 20, 50);
//   doc.text(`Severity: ${report.severity}`, 20, 60);

//   doc.text("Generated by TeleHealth AI System", 20, 80);

//   doc.save("medical-report.pdf");
// };

const downloadPDF = (report) => {
  const doc = new jsPDF();

  // 🔵 Background Header Banner
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, 210, 40, "F");

  // Header Text
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.text("TeleHealth AI Medical Report", 20, 25);

  // Reset color
  doc.setTextColor(0, 0, 0);

  // Date
  doc.setFontSize(12);
  doc.text(`Generated On: ${new Date().toLocaleDateString()}`, 20, 55);

  // 🟦 Symptoms Box
  doc.setFillColor(219, 234, 254);
  doc.rect(15, 65, 180, 30, "F");

  doc.setFontSize(14);
  doc.setTextColor(30, 64, 175);
  doc.text("Symptoms", 20, 75);

  doc.setFontSize(11);
  doc.setTextColor(0);
  doc.text(report.symptoms || "N/A", 20, 85);

  // 🟩 Diagnosis Box
  doc.setFillColor(220, 252, 231);
  doc.rect(15, 105, 180, 30, "F");

  doc.setFontSize(14);
  doc.setTextColor(21, 128, 61);
  doc.text("Diagnosis", 20, 115);

  doc.setFontSize(11);
  doc.setTextColor(0);
  doc.text(report.diagnosis || "N/A", 20, 125);

  // 🟨 Severity Box
  doc.setFillColor(254, 249, 195);
  doc.rect(15, 145, 180, 25, "F");

  doc.setFontSize(14);
  doc.setTextColor(161, 98, 7);
  doc.text("Severity Level", 20, 155);

  doc.setFontSize(11);
  doc.setTextColor(0);
  const severityText = report.severity || "Not Specified";
const severityLines = doc.splitTextToSize(severityText, 160);

doc.text(severityLines, 20, 160);
let severityColor = [0,0,0];

if(report.severity === "High") severityColor = [220,38,38];
if(report.severity === "Medium") severityColor = [234,179,8];
if(report.severity === "Low") severityColor = [34,197,94];

doc.setTextColor(...severityColor);
doc.text(report.severity || "Not Specified", 20, 160);
doc.setTextColor(0,0,0);

  // Footer
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text(
    "This report is generated by TeleHealth AI Symptom Analysis.",
    20,
    190
  );

  doc.text(
    "Consult a certified doctor for proper diagnosis.",
    20,
    196
  );

  doc.save("AI-Medical-Report.pdf");
};

const Reports = () => {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);

  const today = new Date().toLocaleDateString();

  useEffect(() => {
    const fetchReports = async () => {
      try {
        const token = localStorage.getItem("token");

        const res = await axios.get(
          "http://localhost:3000/api/reports",
          {
            headers: {
              Authorization: `Bearer ${token}`,
            },
          }
        );

        setReports(res.data);
      } catch (error) {
        console.log("Error fetching reports:", error);
      } finally {
        setLoading(false);
      }
    };

    fetchReports();
  }, []);

  if (loading) {
    return (
      <div className="w-screen h-screen flex items-center justify-center text-xl font-semibold">
        Loading AI Reports...
      </div>
    );
  }

//   return (
//     <div className="w-screen h-screen bg-linear-to-br from-blue-50 to-white p-10">
//       <h2 className="text-4xl font-bold mb-10 text-center text-blue-800">
//         🧠 AI Recommended Medical Reports
//       </h2>

//       {reports.length === 0 ? (
//         <div className="text-center text-gray-500 text-lg">
//           No reports generated yet.
//         </div>
//       ) : (
//         <div className="grid md:grid-cols-2 gap-8">
//           {reports.map((report) => (
//             <div
//               key={report._id}
//               className="bg-white p-6 rounded-2xl shadow-lg hover:shadow-2xl transition duration-300"
//             >
//               <h3 className="text-2xl font-semibold text-blue-700">
//                 {report.title}
//               </h3>

//               <p className="mt-3 text-gray-600">
//                 {report.description}
//               </p>

//               <p className="mt-2 text-sm text-gray-500">
//                 AI Generated on: {today}
//               </p>

//               <button
//   onClick={() => downloadPDF(report)}
//   className="mt-5 bg-blue-600 text-white px-5 py-2 rounded-lg hover:bg-blue-700 transition"
// >
//   Download PDF
// </button>
//             </div>
//           ))}
//         </div>
//       )}
//     </div>
//   );
return (
  <div className="w-screen h-screen bg-linear-to-br from-blue-50 to-indigo-100 p-10">

    <h2 className="text-4xl font-bold text-center mb-12 text-indigo-700">
      🧠 AI Medical Reports
    </h2>

    {reports.length === 0 ? (
      <div className="text-center text-gray-500 text-lg">
        No reports generated yet.
      </div>
    ) : (
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">

        {reports.map((report) => (
          <div
            key={report._id}
            className="bg-white p-6 rounded-2xl shadow-lg hover:shadow-2xl transition transform hover:-translate-y-2 border border-gray-100"
          >

            <div className="flex justify-between items-center mb-4">
              <span className="text-sm bg-blue-100 text-blue-700 px-3 py-1 rounded-full">
                AI Diagnosis
              </span>

              <span className="text-xs text-gray-400">
                {new Date(report.createdAt).toLocaleDateString()}
              </span>
            </div>

            <h3 className="text-xl font-semibold text-indigo-700 mb-2">
              {report.diagnosis}
            </h3>

            <p className="text-gray-600 mb-2">
              <strong>Symptoms:</strong> {report.symptoms}
            </p>

            <p className="text-gray-600 mb-4">
              <strong>Severity:</strong> {report.severity}
            </p>

            <button
              onClick={() => downloadPDF(report)}
              className="w-full bg-indigo-600 text-white py-2 rounded-lg hover:bg-indigo-700 transition"
            >
              📄 Download Report
            </button>

          </div>
        ))}

      </div>
    )}
  </div>
);

};



export default Reports;

