// import { jsPDF } from "jspdf";
// import { useEffect, useState } from "react";
// import axios from "axios";


// // const downloadPDF = (report) => {
// //   const doc = new jsPDF();

// //   doc.setFontSize(18);
// //   doc.text("AI Medical Report", 20, 20);

// //   doc.setFontSize(12);
// //   doc.text(`Diagnosis: ${report.diagnosis}`, 20, 40);
// //   doc.text(`Symptoms: ${report.symptoms}`, 20, 50);
// //   doc.text(`Severity: ${report.severity}`, 20, 60);

// //   doc.text("Generated by TeleHealth AI System", 20, 80);

// //   doc.save("medical-report.pdf");
// // };

// const downloadPDF = (report) => {
//   const doc = new jsPDF();

//   // 🔵 Background Header Banner
//   doc.setFillColor(37, 99, 235);
//   doc.rect(0, 0, 210, 40, "F");

//   // Header Text
//   doc.setTextColor(255, 255, 255);
//   doc.setFontSize(22);
//   doc.text("TeleHealth AI Medical Report", 20, 25);

//   // Reset color
//   doc.setTextColor(0, 0, 0);

//   // Date
//   doc.setFontSize(12);
//   doc.text(`Generated On: ${new Date().toLocaleDateString()}`, 20, 55);

//   // 🟦 Symptoms Box
//   doc.setFillColor(219, 234, 254);
//   doc.rect(15, 65, 180, 30, "F");

//   doc.setFontSize(14);
//   doc.setTextColor(30, 64, 175);
//   doc.text("Symptoms", 20, 75);

//   doc.setFontSize(11);
//   doc.setTextColor(0);
//   doc.text(report.symptoms || "N/A", 20, 85);

//   // 🟩 Diagnosis Box
//   doc.setFillColor(220, 252, 231);
//   doc.rect(15, 105, 180, 30, "F");

//   doc.setFontSize(14);
//   doc.setTextColor(21, 128, 61);
//   doc.text("Diagnosis", 20, 115);

//   doc.setFontSize(11);
//   doc.setTextColor(0);
//   doc.text(report.diagnosis || "N/A", 20, 125);

//   // 🟨 Severity Box
//   doc.setFillColor(254, 249, 195);
//   doc.rect(15, 145, 180, 25, "F");

//   doc.setFontSize(14);
//   doc.setTextColor(161, 98, 7);
//   doc.text("Severity Level", 20, 155);

//   doc.setFontSize(11);
//   doc.setTextColor(0);
//   const severityText = report.severity || "Not Specified";
// const severityLines = doc.splitTextToSize(severityText, 160);

// doc.text(severityLines, 20, 160);
// let severityColor = [0,0,0];

// if(report.severity === "High") severityColor = [220,38,38];
// if(report.severity === "Medium") severityColor = [234,179,8];
// if(report.severity === "Low") severityColor = [34,197,94];

// doc.setTextColor(...severityColor);
// doc.text(report.severity || "Not Specified", 20, 160);
// doc.setTextColor(0,0,0);

//   // Footer
//   doc.setFontSize(10);
//   doc.setTextColor(120);
//   doc.text(
//     "This report is generated by TeleHealth AI Symptom Analysis.",
//     20,
//     190
//   );

//   doc.text(
//     "Consult a certified doctor for proper diagnosis.",
//     20,
//     196
//   );

//   doc.save("AI-Medical-Report.pdf");
// };

// const Reports = () => {
//   const [reports, setReports] = useState([]);
//   const [loading, setLoading] = useState(true);

//   const today = new Date().toLocaleDateString();

//   useEffect(() => {
//     const fetchReports = async () => {
//       try {
//         const token = localStorage.getItem("token");

//         const res = await axios.get(
//           "http://localhost:3000/api/reports",
//           {
//             headers: {
//               Authorization: `Bearer ${token}`,
//             },
//           }
//         );

//         setReports(res.data);
//       } catch (error) {
//         console.log("Error fetching reports:", error);
//       } finally {
//         setLoading(false);
//       }
//     };

//     fetchReports();
//   }, []);

//   if (loading) {
//     return (
//       <div className="w-screen h-screen flex items-center justify-center text-xl font-semibold">
//         Loading AI Reports...
//       </div>
//     );
//   }

// //   return (
// //     <div className="w-screen h-screen bg-linear-to-br from-blue-50 to-white p-10">
// //       <h2 className="text-4xl font-bold mb-10 text-center text-blue-800">
// //         🧠 AI Recommended Medical Reports
// //       </h2>

// //       {reports.length === 0 ? (
// //         <div className="text-center text-gray-500 text-lg">
// //           No reports generated yet.
// //         </div>
// //       ) : (
// //         <div className="grid md:grid-cols-2 gap-8">
// //           {reports.map((report) => (
// //             <div
// //               key={report._id}
// //               className="bg-white p-6 rounded-2xl shadow-lg hover:shadow-2xl transition duration-300"
// //             >
// //               <h3 className="text-2xl font-semibold text-blue-700">
// //                 {report.title}
// //               </h3>

// //               <p className="mt-3 text-gray-600">
// //                 {report.description}
// //               </p>

// //               <p className="mt-2 text-sm text-gray-500">
// //                 AI Generated on: {today}
// //               </p>

// //               <button
// //   onClick={() => downloadPDF(report)}
// //   className="mt-5 bg-blue-600 text-white px-5 py-2 rounded-lg hover:bg-blue-700 transition"
// // >
// //   Download PDF
// // </button>
// //             </div>
// //           ))}
// //         </div>
// //       )}
// //     </div>
// //   );
// return (
//   <div className="w-screen h-screen bg-linear-to-br from-blue-50 to-indigo-100 p-10">

//     <h2 className="text-4xl font-bold text-center mb-12 text-indigo-700">
//       🧠 AI Medical Reports
//     </h2>

//     {reports.length === 0 ? (
//       <div className="text-center text-gray-500 text-lg">
//         No reports generated yet.
//       </div>
//     ) : (
//       <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">

//         {reports.map((report) => (
//           <div
//             key={report._id}
//             className="bg-white p-6 rounded-2xl shadow-lg hover:shadow-2xl transition transform hover:-translate-y-2 border border-gray-100"
//           >

//             <div className="flex justify-between items-center mb-4">
//               <span className="text-sm bg-blue-100 text-blue-700 px-3 py-1 rounded-full">
//                 AI Diagnosis
//               </span>

//               <span className="text-xs text-gray-400">
//                 {new Date(report.createdAt).toLocaleDateString()}
//               </span>
//             </div>

//             <h3 className="text-xl font-semibold text-indigo-700 mb-2">
//               {report.diagnosis}
//             </h3>

//             <p className="text-gray-600 mb-2">
//               <strong>Symptoms:</strong> {report.symptoms}
//             </p>

//             <p className="text-gray-600 mb-4">
//               <strong>Severity:</strong> {report.severity}
//             </p>

//             <button
//               onClick={() => downloadPDF(report)}
//               className="w-full bg-indigo-600 text-white py-2 rounded-lg hover:bg-indigo-700 transition"
//             >
//               📄 Download Report
//             </button>

//           </div>
//         ))}

//       </div>
//     )}
//   </div>
// );

// };



// export default Reports;

import { jsPDF } from "jspdf";
import { useEffect, useMemo, useState } from "react";
import axios from "axios";
import toast from "react-hot-toast";

const downloadPDF = (report) => {
  const doc = new jsPDF();

  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, 210, 40, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.text("TeleHealth AI Medical Report", 20, 25);

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);
  doc.text(`Generated On: ${new Date().toLocaleDateString()}`, 20, 55);

  doc.setFillColor(219, 234, 254);
  doc.rect(15, 65, 180, 30, "F");
  doc.setFontSize(14);
  doc.setTextColor(30, 64, 175);
  doc.text("Symptoms", 20, 75);
  doc.setFontSize(11);
  doc.setTextColor(0);
  const symptomLines = doc.splitTextToSize(report.symptoms || "N/A", 165);
  doc.text(symptomLines, 20, 85);

  doc.setFillColor(220, 252, 231);
  doc.rect(15, 105, 180, 30, "F");
  doc.setFontSize(14);
  doc.setTextColor(21, 128, 61);
  doc.text("Diagnosis", 20, 115);
  doc.setFontSize(11);
  doc.setTextColor(0);
  const diagnosisLines = doc.splitTextToSize(report.diagnosis || "N/A", 165);
  doc.text(diagnosisLines, 20, 125);

  doc.setFillColor(254, 249, 195);
  doc.rect(15, 145, 180, 25, "F");
  doc.setFontSize(14);
  doc.setTextColor(161, 98, 7);
  doc.text("Severity Level", 20, 155);

  let severityColor = [0, 0, 0];
  if (report.severity === "High") severityColor = [220, 38, 38];
  if (report.severity === "Medium") severityColor = [234, 179, 8];
  if (report.severity === "Low") severityColor = [34, 197, 94];

  doc.setFontSize(11);
  doc.setTextColor(...severityColor);
  doc.text(report.severity || "Not Specified", 20, 163);
  doc.setTextColor(0, 0, 0);

  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text(
    "This report is generated by TeleHealth AI Symptom Analysis.",
    20,
    190
  );
  doc.text("Consult a certified doctor for proper diagnosis.", 20, 196);

  doc.save("AI-Medical-Report.pdf");
};

const Reports = () => {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);

  const stats = useMemo(() => {
    return {
      total: reports.length,
      high: reports.filter((r) => r.severity === "High").length,
      medium: reports.filter((r) => r.severity === "Medium").length,
      low: reports.filter((r) => r.severity === "Low").length,
    };
  }, [reports]);

  useEffect(() => {
    const fetchReports = async () => {
      try {
        const token = localStorage.getItem("token");

        const res = await axios.get("http://localhost:3000/api/reports", {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        });

        setReports(res.data || []);
      } catch (error) {
        console.log("Error fetching reports:", error);
        toast.error("Failed to fetch reports");
      } finally {
        setLoading(false);
      }
    };

    fetchReports();
  }, []);

  const getSeverityStyle = (severity) => {
    switch (severity) {
      case "High":
        return "bg-red-400/20 text-red-200 border border-red-300/30";
      case "Medium":
        return "bg-yellow-400/20 text-yellow-200 border border-yellow-300/30";
      case "Low":
        return "bg-green-400/20 text-green-200 border border-green-300/30";
      default:
        return "bg-white/10 text-white border border-white/20";
    }
  };

  return (
    <div className="w-screen h-full bg-linear-to-br from-[#0f172a] via-[#1e3a8a] to-[#0ea5e9] px-4 py-6 md:px-10">
      <div className="w-full max-w-7xl mx-auto">
        {/* Hero */}
        <div className="rounded-3xl bg-white/10 border border-white/20 backdrop-blur-xl shadow-2xl p-6 md:p-8 text-white">
          <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-6">
            <div>
              <p className="text-blue-200 text-sm font-medium">
                TeleHealth Analytics
              </p>
              <h1 className="text-3xl md:text-5xl font-bold mt-2">
                AI Medical Reports
              </h1>
              <p className="text-blue-100 mt-3 max-w-2xl text-sm md:text-base">
                View your past AI-generated diagnosis reports, check severity,
                and download them as polished PDF reports.
              </p>
            </div>

            <div className="grid grid-cols-2 md:grid-cols-4 gap-3 w-full lg:max-w-2xl">
              <div className="rounded-2xl bg-white/10 border border-white/20 p-4">
                <p className="text-xs text-blue-200">Total Reports</p>
                <h3 className="text-2xl font-bold mt-1">{stats.total}</h3>
              </div>
              <div className="rounded-2xl bg-white/10 border border-white/20 p-4">
                <p className="text-xs text-blue-200">High</p>
                <h3 className="text-2xl font-bold mt-1">{stats.high}</h3>
              </div>
              <div className="rounded-2xl bg-white/10 border border-white/20 p-4">
                <p className="text-xs text-blue-200">Medium</p>
                <h3 className="text-2xl font-bold mt-1">{stats.medium}</h3>
              </div>
              <div className="rounded-2xl bg-white/10 border border-white/20 p-4">
                <p className="text-xs text-blue-200">Low</p>
                <h3 className="text-2xl font-bold mt-1">{stats.low}</h3>
              </div>
            </div>
          </div>
        </div>

        {/* Quick cards */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mt-6">
          <div className="rounded-2xl bg-white/10 border border-white/20 backdrop-blur-xl p-4 text-white">
            <p className="text-xs text-blue-200">Insights</p>
            <h3 className="text-lg font-semibold mt-1">AI Diagnosis History</h3>
          </div>
          <div className="rounded-2xl bg-white/10 border border-white/20 backdrop-blur-xl p-4 text-white">
            <p className="text-xs text-blue-200">Severity</p>
            <h3 className="text-lg font-semibold mt-1">Health Risk Tracking</h3>
          </div>
          <div className="rounded-2xl bg-white/10 border border-white/20 backdrop-blur-xl p-4 text-white">
            <p className="text-xs text-blue-200">Export</p>
            <h3 className="text-lg font-semibold mt-1">Download PDF Report</h3>
          </div>
        </div>

        {/* Main panel */}
        <div className="mt-6 rounded-3xl bg-white/10 border border-white/20 backdrop-blur-xl shadow-2xl p-4 md:p-6">
          {loading ? (
            <div className="flex flex-col items-center justify-center py-24 text-white">
              <div className="w-12 h-12 border-4 border-white/30 border-t-white rounded-full animate-spin mb-4"></div>
              <p className="text-lg font-medium">Loading AI reports...</p>
            </div>
          ) : reports.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-24 text-center text-white">
              <div className="text-6xl mb-4">🧠</div>
              <h2 className="text-2xl md:text-3xl font-bold mb-2">
                No reports generated yet
              </h2>
              <p className="text-blue-100 mb-6 max-w-md">
                Once you analyze symptoms, your AI-generated reports will appear
                here for review and download.
              </p>
              <button
                onClick={() => toast("Start by analyzing symptoms")}
                className="px-6 py-3 rounded-xl bg-linear-to-r from-blue-500 to-purple-500 text-white font-semibold hover:scale-[1.02] transition"
              >
                Generate a Report
              </button>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
              {reports.map((report) => (
                <div
                  key={report._id}
                  className="rounded-3xl bg-white/10 border border-white/20 backdrop-blur-lg p-5 md:p-6 text-white shadow-xl hover:scale-[1.01] transition"
                >
                  <div className="flex items-center justify-between gap-3 mb-4">
                    <span className="px-3 py-1 rounded-full text-xs font-semibold bg-blue-400/20 text-blue-100 border border-blue-300/20">
                      AI Diagnosis
                    </span>

                    <span className="text-xs text-blue-200">
                      {new Date(report.createdAt).toLocaleDateString()}
                    </span>
                  </div>

                  <h3 className="text-xl font-bold mb-3">
                    {report.diagnosis}
                  </h3>

                  <div className="space-y-3">
                    <div className="rounded-2xl bg-white/10 p-4">
                      <p className="text-xs text-blue-200">Symptoms</p>
                      <p className="mt-1 text-sm">{report.symptoms}</p>
                    </div>

                    <div className="flex items-center justify-between gap-3">
                      <div className="rounded-2xl bg-white/10 p-4 flex-1">
                        <p className="text-xs text-blue-200">Severity</p>
                        <div className="mt-2">
                          <span
                            className={`px-3 py-1 rounded-full text-xs font-semibold ${getSeverityStyle(
                              report.severity
                            )}`}
                          >
                            {report.severity || "Not Specified"}
                          </span>
                        </div>
                      </div>
                    </div>
                  </div>

                  <button
                    onClick={() => downloadPDF(report)}
                    className="mt-5 w-full py-3 rounded-xl bg-linear-to-r from-indigo-500 to-purple-500 text-white font-semibold hover:scale-[1.02] transition"
                  >
                    📄 Download Report
                  </button>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default Reports;